# Generated by Django 3.2.7 on 2022-05-08 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20220415_0957'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('surname', models.CharField(max_length=55, verbose_name='Surname')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone number')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/images_of_users', verbose_name='Image')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
            options={
                'verbose_name': 'Info user',
                'verbose_name_plural': 'Info users',
            },
        ),
    ]
